### ISSUE TITLE
Backend: No proper Database setup guide

### ISSUE THREAD

**Issue by dhananjaypai08** [CMPN-CODECELL/URL-Shortener#12]
- Need of adding a full detailed setup guide for setting up the mysql database in one's own local set. 
- Make changes directly to the Readme file or a new .md file which we can link in our main readme file for setting up database for this project.
- Solver has to be aware that .env file is ignored as it contains sensitive data like db passwords and provide the guide accordingly

**Comment by Denzil10** [comment]
Hey @dhananjaypai08  I would like to work on this

**Comment by dhananjaypai08** [comment]
Go ahead

**Comment by Denzil10** [comment]
Have added the setup of the config file

are the DB steps enough or are images needed?
will also add a note regarding why .env files are being used.
