### ISSUE TITLE
Backend: Extra numbers being displayed on the history page

### ISSUE THREAD

**Issue by JapneetRajput** [CMPN-CODECELL/URL-Shortener#3]
There is only 1 link but the index for the 2nd link is also displayed

![History](https://user-images.githubusercontent.com/82120186/193450262-3312055a-92d9-478a-ad7c-ecd1649b703c.png)

**Comment by aniket2003** [comment]
Hey @JapneetRajput I would like to work on this issue can you please assign it to me.

**Comment by JapneetRajput** [comment]
Done @aniket2003

**Comment by aniket2003** [comment]
@JapneetRajput I am sorry ,I was not able to solve the resolve the issue , sorry for the inconvenience I caused.

**Comment by JapneetRajput** [comment]
No it's fine @aniket2003 atleast you tried

I ll put a more detailed explanation for the issue

**Comment by Denzil10** [comment]
Hey @JapneetRajput I would like to work on this issue

**Comment by JapneetRajput** [comment]
Done @Denzil10
